# Generated by Django 2.2.15 on 2021-01-07 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_meta', '0003_auto_20201125_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemeta',
            name='is_prereq',
        ),
    ]
