version: 2.1

executors:
  docker-executor: # a reusable executor
    docker:
      - image: cimg/python:3.5-node
        auth:
          username: jw3759142
          password: $DOCKERHUB_PASSWORD
      - image: circleci/mongo:4.1.12-bionic
        auth:
          username: jw3759142
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/edx-platform

commands:
  common-steps: # a reusable command
    steps:
      - checkout
      - restore_cache:
          key: abc13-{{ checksum "requirements/edx/testing.txt" }}-{{ checksum "requirements/adg/base.txt"
            }}-{{ checksum "requirements/edx/coverage.txt" }}-{{ checksum "package.json" }}
      - run:
          name: Download requirements
          no_output_timeout: 25m
          command: |
            wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
            echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.4 multiverse" \
            | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
            sudo apt-get update
            sudo apt-get install -y mongodb-org-shell=4.4.1 jq

            pip install --exists-action w -r requirements/edx/testing.txt
            pip install --exists-action w -r requirements/adg/base.txt
      - run:
          name: Run all tests
          command: |
            BASE_BRANCH=$(curl https://api.github.com/repos/OmnipreneurshipAcademy/edx-platform/pulls/14 | jq -r ".base.ref")
            BASE_BRANCH="origin/${BASE_BRANCH}"
            if [ "$CIRCLE_JOB" == "adg-test" ]; then
              source adg_pipelines/scripts/run-adg-test.sh "$BASE_BRANCH"
            else
              source adg_pipelines/scripts/run-edx-test.sh "$BASE_BRANCH"
            fi
      - save_cache:
          key: abc13-{{ checksum "requirements/edx/testing.txt" }}-{{ checksum "requirements/adg/base.txt"
            }}-{{ checksum "requirements/edx/coverage.txt" }}-{{ checksum "package.json" }}
          paths:
            - "/home/circleci/.pyenv/versions/3.5.10/bin/"
            - "/home/circleci/.pyenv/versions/3.5.10/lib/"
            - "/home/circleci/.cache/pip"
            - "/home/circleci/project/node_modules"
      - store_artifacts:
          path: reports
      - store_artifacts:
          path: test_root/log
      - store_test_results:
          path: reports

jobs:
  adg-test:
    executor: docker-executor
    steps:
      - common-steps
      - run:
          name: Upload report to Codecov
          command: |
            bash <(curl -s https://codecov.io/bash) -f reports/coverage.xml
  edx-test:
    executor: docker-executor
    steps:
      - common-steps

workflows:
  main:
    jobs:
      - adg-test:
          context:
            - adg-context
      - edx-test:
          context:
            - adg-context
          requires:
            - adg-test
