# Generated by Django 2.2.17 on 2021-07-13 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userapplication',
            name='internal_admin_note',
        ),
        migrations.RemoveField(
            model_name='userapplication',
            name='reviewed_by',
        ),
        migrations.CreateModel(
            name='MessageForApplicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('application_status', models.CharField(choices=[('waitlist', 'Waitlist'), ('accepted', 'Accepted')], max_length=8, verbose_name='Application Status')),
                ('message', models.TextField(verbose_name='Message For Applicant')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('user_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_for_applicant', to='applications.UserApplication', verbose_name='User Application')),
            ],
            options={
                'ordering': ('application_status',),
            },
        ),
        migrations.CreateModel(
            name='AdminNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('note', models.TextField(verbose_name='Note')),
                ('saved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Saved By')),
                ('user_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='applications.UserApplication', verbose_name='User Application')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
