# Generated by Django 2.2.15 on 2020-12-02 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('applications', '0003_user_application_update_business_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessline',
            name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
