# Generated by Django 2.2.15 on 2020-12-02 19:59

from django.db import migrations, models
import rules.contrib.models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_businessline_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
