# Generated by Django 2.2.15 on 2020-12-03 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessline',
            name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bu_group', to='auth.Group'),
        ),
    ]
