name: Detect Transifex translations

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - develop

jobs:
  generate-translations:
    name: Detect changed source and generate Transifex translations
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.5

      - name: Add translation requirements file
        run: |
          touch requirements/adg/translations.txt
          echo 'paver==1.3.4' >> requirements/adg/translations.txt
          echo 'transifex-client==0.13.4' >> requirements/adg/translations.txt
          echo 'edx-i18n-tools==0.5.3' >> requirements/adg/translations.txt
          echo 'django-statici18n==1.9.0' >> requirements/adg/translations.txt
          echo 'babel==2.8.0' >> requirements/adg/translations.txt
          echo 'mako==1.0.2' >> requirements/adg/translations.txt
          echo 'git+https://github.com/edx/django-babel-underscore.git@37705f7377a4d0a4e673f1431895ce28a8860cd7#egg=django-babel-underscore==0.6.0' >> requirements/adg/translations.txt
          echo 'git+https://github.com/Zegocover/enmerkar.git@dbc113798aa4beabdfa2d00e6fef48248eb0f185#egg=django-babel==0.6.3.dev0' >> requirements/adg/translations.txt
          echo '-e git+https://github.com/edx/django-wiki.git@0.0.27#egg=django-wiki' >> requirements/adg/translations.txt
          echo 'polib==1.1.0' >> requirements/adg/translations.txt
          echo 'edx_proctoring_proctortrack' >> requirements/adg/translations.txt
          echo 'watchdog==0.10.2' >> requirements/adg/translations.txt
          echo 'python-memcached==1.59' >> requirements/adg/translations.txt
          echo 'lazy==1.4' >> requirements/adg/translations.txt
          echo 'wrapt==1.11.2' >> requirements/adg/translations.txt

      - name: Cache python requirements
        uses: actions/cache@v2
        id: cache-python-requirements
        with:
          path: /opt/hostedtoolcache/Python/
          key: |
            ${{ hashFiles('requirements/adg/translations.txt') }}-1

      - name: Install requirements
        if: steps.cache-python-requirements.outputs.cache-hit != 'true'
        run: |
          sudo apt-get install libxmlsec1-dev pkg-config gettext
          sudo apt-get update
          python3 -m pip install pip==20.0.2
          python3 -m pip install setuptools==50.3.0
          python3 -m pip install wheel==0.35.1
          pip install --disable-pip-version-check --exists-action w -r requirements/adg/translations.txt

      - name: Clone adg-edx-theme repo
        uses: actions/checkout@v2
        continue-on-error: true
        with:
          repository: OmnipreneurshipAcademy/adg-edx-theme
          path: ./themes
          ref: ${{ github.head_ref }}
          token: ${{ secrets.ADG_THEME_ACCESS_TOKEN }}

      - name: Pull latest translations
        id: pull-latest-translations
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}
        run: tx pull -l ar

      - name: Generate translations for changed source
        id: generate-new-translations
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}
        run: make extract_translations

      - name: Merge all the translations
        id: merge-translations
        run: msgmerge conf/locale/ar/LC_MESSAGES/django-partial.po conf/locale/en/LC_MESSAGES/django-partial.po --update && msgmerge conf/locale/ar/LC_MESSAGES/django-partial.po conf/locale/en/LC_MESSAGES/django-partial.po --update && msgmerge conf/locale/ar/LC_MESSAGES/django-studio.po conf/locale/en/LC_MESSAGES/django-studio.po --update && msgmerge conf/locale/ar/LC_MESSAGES/djangojs-partial.po conf/locale/en/LC_MESSAGES/djangojs-partial.po --update && msgmerge conf/locale/ar/LC_MESSAGES/djangojs-studio.po conf/locale/en/LC_MESSAGES/djangojs-studio.po --update && msgmerge conf/locale/ar/LC_MESSAGES/mako.po conf/locale/en/LC_MESSAGES/mako.po --update && msgmerge conf/locale/ar/LC_MESSAGES/mako-studio.po conf/locale/en/LC_MESSAGES/mako-studio.po --update && msgmerge conf/locale/ar/LC_MESSAGES/underscore.po conf/locale/en/LC_MESSAGES/underscore.po --update && msgmerge conf/locale/ar/LC_MESSAGES/underscore-studio.po conf/locale/en/LC_MESSAGES/underscore-studio.po --update && msgmerge conf/locale/ar/LC_MESSAGES/wiki.po conf/locale/en/LC_MESSAGES/wiki.po --update

      - name: Generate i18n files
        id: generate-i18n-files
        run: paver i18n_fastgenerate

      - name: Commit changed translation files
        id: commit-and-push-generated-files
        uses: EndBug/add-and-commit@v6
        with:
          message: 'Add changed translation files'
          add: "['conf/locale/ar/LC_MESSAGES/django.mo',
                 'conf/locale/ar/LC_MESSAGES/django.po',
                 'conf/locale/ar/LC_MESSAGES/djangojs.po',
                 'conf/locale/ar/LC_MESSAGES/djangojs.mo',
                 'lms/static/js/i18n/ar/djangojs.js']"
          push: true
          token: ${{ secrets.GITHUB_TOKEN }}
          signoff: true

      - name: Post progress report on PR
        uses: mshick/add-pr-comment@v1
        with:
          message: |
              New translations have been generated for the changed source. :v:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          allow-repeats: true
        if: steps.commit-and-push-generated-files.outputs.committed == 'true'
                && steps.commit-and-push-generated-files.outputs.pushed == 'true'
