name: Push translations to Transifex

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - master

jobs:
  push-translations:
    name: Push Translations
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.5
        if: env.GIT_DIFF

      - name: Cache python requirements
        uses: actions/cache@v2
        id: cache-python-requirements
        with:
          path: /opt/hostedtoolcache/Python/
          key: |
            ${{ hashFiles('requirements/adg/base.txt') }}
        if: env.GIT_DIFF

      - name: Install requirements
        run: |
          sudo apt-get install libxmlsec1-dev pkg-config
          sudo apt-get update
          python3 -m pip install pip==20.0.2
          python3 -m pip install setuptools==50.3.0
          python3 -m pip install wheel==0.35.1
          pip install --disable-pip-version-check --exists-action w -r requirements/adg/base.txt
        if: env.GIT_DIFF && steps.cache-python-requirements.outputs.cache-hit != 'true'

      - name: Clone adg-edx-theme repo
        uses: actions/checkout@v2
        with:
          repository: OmnipreneurshipAcademy/adg-edx-theme
          path: ./themes
          token: ${{ secrets.ADG_THEME_ACCESS_TOKEN }}

      - name: Push new tranlations to Transifex
        id: push_generated_translations
        with:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}
        run: tx push -s -t
